### ISSUE TITLE
Fix wrong base URL in frontend production build

### ISSUE THREAD

**Issue by tiadams** [SCAI-BIO/index#58]
Should be pulled from production angular env but uses default instead

**Comment by tiadams** [comment]
@mehmetcanay 

I get an syntax error when I add 
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],

**Comment by mehmetcanay** [comment]
The Angular documentation for [v17](https://v17.angular.io/guide/build) also shows this. Did you generate environments with ng generate or did you create the folder yourself? If the latter, maybe we need to specify the folder location in one of the configuration files.
